# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TreeWiki
email: chanwook.god@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  박찬욱의 개인 위키입니다. (현재 공사 중...)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nodomain.com" # the base hostname & protocol for your site

twitter_username: _chanwook
github_username:  chanwookpark
facebook_username: chanwook.park.1

# Build settings
markdown: kramdown

highlighter: rouge
safe: true
lsi: true

# Asciidoctor - github page가 기본적으로 지원을 하지 않고 복잡하게 CI 등을 돌려햐해서 포기.. jekyll 기본 템플릿을 사용하자..
# 참조: https://github.com/asciidoctor/jekyll-asciidoc
#asciidoc: {}
#asciidoctor: {}
