title: TreeWiki
baseurl: ""
url: "http://chanwookpark.github.io"

date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
safe: true
lsi: true

gems:
  - jekyll-toc

kramdown:
  input: GFM
  hard_wrap: false
  toc_levels: 1..4

plugins:
  - jekyll-sitemap
  - jekyll-feed
