title: TreeWiki
baseurl: ""
url: "http://chanwookpark.github.io"

date_format: "%Y-%m-%d"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
safe: true
lsi: true

kramdown:
  input: GFM
  hard_wrap: false
